- name: Play Variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print play variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      
      
      - name: Demo Play 1
  hosts: all
  tasks:
   - name: Print Hello
     ansible.builtin.debug:
        msg: Hello World Testing Ansible!