- name: Demo Play 1
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
   - name: Print Hello
     ansible.builtin.debug:
        msg: URL = {{ URL }}
        
  ## vars_files only works on play level    
- name: Play Variables from Files
  hosts: localhost
  vars_files:
   - 2-vars.yml
  tasks:
   - name: Print Variables from File
     ansible.builtin.debug:
        msg: URL = {{ URL }}        
        
        
- name: Task level variables
 hosts: localhost
 tasks:
  - name:Print task level variables
 vars: 
    URL: task.example.com
    ansible.builtin.debug:
    msg: URL = {{ URL }}
    