- name: Demo Play 1
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
   - name: Print Hello
     ansible.builtin.debug:
        msg: URL = {{ URL }}
        
  ## vars_files only works on play level    
- name: Play Variables from Files
  hosts: localhost
  vars_files:
   - 2-vars.yml
  tasks:
   - name: Print Variables from File
     ansible.builtin.debug:
        msg: URL = {{ URL }}        
        
        
- name: Task level variables
  hosts: localhost
  tasks:
   - name: Play Variables Task
     vars: 
      URL: task.example.com
     ansible.builtin.debug:
      msg: URL = {{ URL }}
    
- name: Inventory level variables
  hosts: localhost
  tasks:
   - name: Play Variables from Inventory    ##localhost ansible_user=centos ansible_password=DevOps321 URL=inventory.example.com in /tmp/inv
     ansible.builtin.debug:
      msg: URL = {{ URL }}
      
      ## command for the inventory--- ansible-playbook -i /tmp/inv 3-vars.yml 
      ## command for the cli --- ansible-playbook -i /tmp/inv 3-vars.yml -e URL=cli.example.com

- name: Inventory level variables
  hosts: localhost
  tasks:
   - name: Play Variables from Inventory
     ansible.builtin.debug:
      msg: "URL = {{ URL }}, Hostname of Server = {{ ansible_hostname}}"

      

