- name: loops demo
  hosts: localhost
  tasks:
    - name: Print fruit name
      debug:
        msg: Fruit Name - {{ item }}
        
      loop:
        - apple
        - banana
        - orange
        - mango
        
# for i in Apple,Banana, do echo $i